### ISSUE TITLE
Second pure js implementation

### ISSUE THREAD

**Issue by dcousens** [cryptocoinjs/secp256k1-node#115]
@fanatid is the plan here to roll this implementation out instead of `elliptic`?
I suppose it might be simpler than using `elliptic` inline,  but,  we might need to weight up the pros/cons of such an action.

What were your plans here?

**Comment by dcousens** [comment]
Why wasn't `bn.js` used for the "pure js" impl?
You did a new/derived implementation there too?

**Comment by fanatid** [comment]
It was interesting for me create library from scratch, of course I looked at `bn.js`/`elliptic` in process. I also though that my impl will have better performance, but performance gain was too small. For understanding how things works and for review my is better because have much less code. But I'm afraid that nobody review my impl, while `elliptic`/`bn.js` was reviewed by a lot of people (at least I think so).
