### ISSUE TITLE
Benchmarking Performance Issue

### ISSUE THREAD

**Issue by chrishickey** [cryptocoinjs/secp256k1-node#146]
Hello, thank you for making such a great library publicly available. I am having trouble getting the signing/verifying performance benchmarks outlined in the performance section of your wiki. When I build and run your project these are the results I get

![image](https://user-images.githubusercontent.com/6553063/58233397-f31eb680-7d76-11e9-8c53-5c0b057ed97c.png)

But looking at your wiki these are the benchmarks I should get

![image](https://user-images.githubusercontent.com/6553063/58233464-22352800-7d77-11e9-9b29-43e4c99e0f0a.png)

Do you know what might explain this difference in performance?

**Comment by fanatid** [comment]
Oh, there a ton of things from which numbers will be depends... CPU / OS / node version / C++ compiler version / secp256k1 version / secp256k1 js code version.
Your numbers from becnhmark looks better, is this a problem? :laughing:

**Comment by chrishickey** [comment]
Thank you for your fast response. Maybe I'm a little confused but I'm only getting 1,405 sign operations per second and 348 verify operations per second. According to this link :

https://github.com/cryptocoinjs/secp256k1-node/wiki/Benchmarks

i was hoping it might be possible to get over 10,000 sign/verify ops/sec

**Comment by fanatid** [comment]
bindings / secp256k1js / elliptic -- all 3 these things located in this project
bindings used by default if they was successfully build
secp256k1js is not used now, I created this, but as I know not a lot of people checked it, so now
elliptic used as native js implementation by default, this is good choice, since elliptic is definitely checked by a lot of devs and used by many systems a lot of time

so, if you will use this package in node.js (not browser) and bindings will be compiled for you, you should getn over 10k sign/verigy ops/sec

**Comment by chrishickey** [comment]
This is what I run from the beginning to get those benchmarks in nodejs :

git clone https://github.com/cryptocoinjs/secp256k1-node.git
cd secp256k1-node
git submodule update --init
npm install
cd benchmarks
npm install .
node index.js

I don't see any errors when running these installs. Is there any step/pre-requisite you can think of that I may need in order to increase the performance from 100 to 10,000 ops/sec??

**Comment by fanatid** [comment]
Please try version 4.0.0
https://github.com/cryptocoinjs/secp256k1-node/pull/160
