### ISSUE TITLE
Exporting elliptic wrapper

### ISSUE THREAD

**Issue by alcuadrado** [cryptocoinjs/secp256k1-node#153]
Hi @fanatid!

I'm opening this issue because there's a lot of interest among Ethereum dev tools developers and some other big projects on removing native dependencies, and this is one of the most used ones. The reason for this is that some of them break when new node versions are released, are complicated to use on windows, and many people don't have the necessary tooling for using them. For example, a member of the Embark team mentioned that they are a constant source of problems when they give workshops, as most assistants don't have a proper dev environment.

To help on this, I'm starting to work in [this project](https://github.com/alcuadrado/ethereum-cryptography), which is a single package with all the cryptographic primitives used in Ethereum that doesn't have native dependencies. It's just a collection of dependencies, not rolling my own crypto. If users want to choose to use native dependencies, they can install [a second package](https://github.com/alcuadrado/ethereum-cryptography/tree/master/packages/ethereum-cryptography-native), and that one is used instead. The idea is to convince the different projects to use it (many of them already showed their interest), and to free future tool and library developers from having to vet different dependencies, and preventing them from accidentally reintroducing native dependencies.

I was planning to use elliptic for the pure-js version of `secp256k1`, and this library for the native version. This, of course, needs some work normalizing them, as their APIs must match. I just found that you already did this work, but I can't do a `require(secp256k1/elliptic)`, because installing this project means compiling the native version. I was wondering if you are open to exporting this normalization layer, maybe something like `elliptic-secp256k1`. 

Thanks!

**Comment by fanatid** [comment]
Hi @alcuadrado.

Yeah, I see issues all the time about bindings, honestly it's not clear why they raised. Node.js releases with big changes in v8 (like `Maybe` API version) happened not so often, so code not require changes usually. I think in most cases developers just do not install required environment for building. But I think, probably, right way here educated people, not give them slow versions.

Compilation for each new v8 version in node not required with [N-API](https://nodejs.org/api/n-api.html) and I have plans about migrating some crypto projects to it. For example if it will be possible build projects for n-api version 1 and include prebuilds* to published package such problem should not be raised anymore. (*there should be right setup CI for building for mac/linux/windows for node/electron with easily verification of such prebuilds by anybody, previously this was exists without verification and was removed now)

Also, this project and [cryptocoinjs/keccak](https://github.com/cryptocoinjs/keccak) should be OK with failed compilation, because JS fallback used in such case and install should return code `0` because install script end with `|| true`.

If `secp256k1/elliptic` good for you, maybe you add it to [alcuadrado/ethereum-cryptography](https://github.com/alcuadrado/ethereum-cryptography) as git submodule? (but probably this will not be very helpful)

**Comment by alcuadrado** [comment]
Thanks for your quick reply @fanatid!

> I think in most cases developers just do not install required environment for building.

Yeah, I suspect the same thing.


> But I think, probably, right way here educated people, not give them slow versions.

That's also a valid point of view. With my library, I'm trying to lib up to the user what to use. I guess it's worth mentioning that it's mostly focused on dev tools and web stuff, so maybe this approach will work.

> Compilation for each new v8 version in node not required with [N-API](https://nodejs.org/api/n-api.html) and I have plans about migrating some crypto projects to it

I had no idea about this, sounds super cool.

> Also, this project and [cryptocoinjs/keccak](https://github.com/cryptocoinjs/keccak) should be OK with failed compilation, because JS fallback used in such case and install should return code `0` because install script end with `|| true`.

I know that, and I'm very grateful for it. I've lost too much time with other native dependencies that don't do the same. I was using `sha3` in my library but will consider migrating into  https://github.com/cryptocoinjs/keccak

> If `secp256k1/elliptic` good for you, maybe you add it to [alcuadrado/ethereum-cryptography](https://github.com/alcuadrado/ethereum-cryptography) as git submodule? (but probably this will not be very helpful)

Thanks for this suggestion! It worked 🎉 I add it as a submodule and used rollup to bundle just the bits that adapt the API. You can take a look at it [here](https://github.com/alcuadrado/ethereum-cryptography/blob/master/packages/ethereum-cryptography/elliptic-secp256k1-config/rollup.config.js).

I'll close this issue as it's already solved. Thanks!
